import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useEffect, useState } from 'react';
import Button from '@/components/Button';
import Input from '@/components/Input';
import Header from '@/components/Header';
import { useRouter } from 'next/router';

export default function Home() {

  const [user, setUser] = useState('');
  const router = useRouter();

    useEffect(() => {
      const fetchData = async () => {
        const url = 'http://localhost:3000/api/user';
        const data = await fetch(url);
        const data_json = await data.json();
        setUser(data_json.results.user);
      }
      fetchData();
    });

  const redirectPage = () => {
    router.push('/about/lucas');
  }

  return (
    <>
      <Head>
        <title>Testando nextJs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <div>
          {user && <p>{user}</p>}
          <Input />
          <Button redirectPage={ redirectPage } />
        </div>
      </main>
    </>
  )
}
